package com.ferronor.sic.compras.vista;

import com.ferronor.sic.compras.logica.OrdenCompraService;
import com.ferronor.sic.compras.modelo.Compra;
import com.ferronor.sic.compras.modelo.DetalleCompra;
import com.ferronor.sic.compras.modelo.EstadoOrdenCompra;
import com.ferronor.sic.compras.modelo.OrdenCompra;
import com.ferronor.sic.maestros.logica.FormaPagoService;
import com.ferronor.sic.maestros.logica.ProductoService;
import com.ferronor.sic.maestros.logica.ProveedorService;
import com.ferronor.sic.maestros.modelo.FormaPago;
import com.ferronor.sic.maestros.modelo.Producto;
import com.ferronor.sic.maestros.modelo.Proveedor;
import com.ferronor.sic.procesos.ProcesoCompra;
import com.ferronor.sic.shared.FrmBase;
import com.ferronor.sic.shared.RespuestaOperacion;
import com.ferronor.sic.shared.ServiceFactory;
import com.ferronor.sic.shared.SesionUsuario;
import com.ferronor.sic.shared.ui.ComboAutoFiltro;
import com.ferronor.sic.tesoreria.logica.TesoreriaService;
import com.ferronor.sic.tesoreria.modelo.Caja;
import com.ferronor.sic.tesoreria.modelo.CuentaBancaria;
import com.ferronor.sic.util.CalculadoraImpuestos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import com.ferronor.sic.compras.modelo.DetalleOrdenCompra;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Usuario
 */
public class FrmCompras extends javax.swing.JFrame {

    // Services y ProcesoCompra vía ServiceFactory — igual patrón que FrmVentas.
    private final ProveedorService proveedorService = ServiceFactory.proveedorService();
    private final ProductoService productoService = ServiceFactory.productoService();
    private final FormaPagoService formaPagoService = ServiceFactory.formaPagoService();
    private final OrdenCompraService ordenCompraService = ServiceFactory.ordenCompraService();
    private final TesoreriaService tesoreriaService = ServiceFactory.tesoreriaService();
    private final ProcesoCompra procesoCompra = ServiceFactory.procesoCompra();

    private final List<DetalleCompra> detalles = new ArrayList<>();
    private final DefaultTableModel modeloDetalle = new DefaultTableModel(
            new Object[]{
                "PRODUCTO",
                "CANTIDAD",
                "COSTO UNIT. (SIN IGV)",
                "SUBTOTAL"
            }, 0) {

        @Override
        public boolean isCellEditable(int fila, int columna) {
            return columna == 2;
        }
    };

    private Caja cajaAbierta;
    private CuentaBancaria cuentaBancariaActiva;
    private List<OrdenCompra> ordenesAprobadas = new ArrayList<>();

    private static final DecimalFormat FORMATO_MONEDA = new DecimalFormat("#,##0.00");

    /**
     * Creates new form FrmVentas
     */
    public FrmCompras() {
        super("COMPRAS");
        initComponents();
        configurarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpBtnFormaPago = new javax.swing.ButtonGroup();
        pnlSuperior = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblNombreVend = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        pnlCliente = new javax.swing.JPanel();
        pnlClienteBuscado = new javax.swing.JPanel();
        lblDocumento = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        tblTelefono = new javax.swing.JLabel();
        pnlOrdenCompra = new javax.swing.JPanel();
        cmbOrdenCompra = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        pnlDetalleProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetProducto = new javax.swing.JTable();
        pnlAgregarProd = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        txtPrecioUnitario = new javax.swing.JTextField();
        spnCantidad = new javax.swing.JSpinner();
        cmbProductos = new javax.swing.JComboBox<>();
        pnlValidaciones = new javax.swing.JPanel();
        txtValEj1 = new javax.swing.JTextField();
        txtValEj2 = new javax.swing.JTextField();
        txtValEj3 = new javax.swing.JTextField();
        pnlComprobante = new javax.swing.JPanel();
        lblNroFactura = new javax.swing.JLabel();
        pnlFormaPago = new javax.swing.JPanel();
        cmbFormasPago = new javax.swing.JComboBox<>();
        pnlDestinoPago = new javax.swing.JPanel();
        rbtnCaja = new javax.swing.JRadioButton();
        rbtnCtaBancaria = new javax.swing.JRadioButton();
        pnlTotales = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblCantSubTotal = new javax.swing.JLabel();
        lblIGV = new javax.swing.JLabel();
        lblCantIGV = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotal = new javax.swing.JLabel();
        lblCantTotal = new javax.swing.JLabel();
        btnRegistrarVenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFacturaProveedor = new javax.swing.JTextField();
        lblFechaCompra = new javax.swing.JLabel();
        jdcFechaCompra = new com.toedter.calendar.JDateChooser();
        pnlPlazoDias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblUsuario.setText("USUARIO:");

        lblNombreVend.setText("Nombre A. (sesión activa)");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblFecha.setText("FECHA:");

        lblFechaHora.setText("dd/mm/yy - 19:18 p.m.");

        lblCaja.setText("Caja Principal - Abierta");

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblNombreVend))
                .addGap(23, 23, 23)
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(lblFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCaja)
                .addGap(15, 15, 15))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(lblFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreVend)
                            .addComponent(lblFechaHora)))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCaja)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "01. PROVEEDOR Y ORDEN DE COMPRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        pnlClienteBuscado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDocumento.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        lblDocumento.setText("RUC/DNI 0123456789");

        lblNombreCliente.setText("Nombre del Cliente (Persona o Empresa)");

        tblTelefono.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        tblTelefono.setText("Tel. 985 466 883");

        javax.swing.GroupLayout pnlClienteBuscadoLayout = new javax.swing.GroupLayout(pnlClienteBuscado);
        pnlClienteBuscado.setLayout(pnlClienteBuscadoLayout);
        pnlClienteBuscadoLayout.setHorizontalGroup(
            pnlClienteBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteBuscadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlClienteBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteBuscadoLayout.createSequentialGroup()
                        .addComponent(lblNombreCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlClienteBuscadoLayout.createSequentialGroup()
                        .addComponent(lblDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tblTelefono)))
                .addContainerGap())
        );
        pnlClienteBuscadoLayout.setVerticalGroup(
            pnlClienteBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteBuscadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(tblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlOrdenCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDEN DE COMPRA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        javax.swing.GroupLayout pnlOrdenCompraLayout = new javax.swing.GroupLayout(pnlOrdenCompra);
        pnlOrdenCompra.setLayout(pnlOrdenCompraLayout);
        pnlOrdenCompraLayout.setHorizontalGroup(
            pnlOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbOrdenCompra, 0, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOrdenCompraLayout.setVerticalGroup(
            pnlOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenCompraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cmbOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClienteBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlOrdenCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlClienteBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalleProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "02. DETALLE DE PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        tblDetProducto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tblDetProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "P. UNIT (CON IGV)", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetProducto);

        javax.swing.GroupLayout pnlDetalleProductoLayout = new javax.swing.GroupLayout(pnlDetalleProducto);
        pnlDetalleProducto.setLayout(pnlDetalleProductoLayout);
        pnlDetalleProductoLayout.setHorizontalGroup(
            pnlDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlDetalleProductoLayout.setVerticalGroup(
            pnlDetalleProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleProductoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pnlAgregarProd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAgregarProducto.setBackground(new java.awt.Color(51, 102, 0));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarProdLayout = new javax.swing.GroupLayout(pnlAgregarProd);
        pnlAgregarProd.setLayout(pnlAgregarProdLayout);
        pnlAgregarProdLayout.setHorizontalGroup(
            pnlAgregarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProducto)
                .addContainerGap())
        );
        pnlAgregarProdLayout.setVerticalGroup(
            pnlAgregarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgregarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlValidaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "03. VALIDACIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        javax.swing.GroupLayout pnlValidacionesLayout = new javax.swing.GroupLayout(pnlValidaciones);
        pnlValidaciones.setLayout(pnlValidacionesLayout);
        pnlValidacionesLayout.setHorizontalGroup(
            pnlValidacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlValidacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValEj1)
                    .addComponent(txtValEj2)
                    .addComponent(txtValEj3))
                .addContainerGap())
        );
        pnlValidacionesLayout.setVerticalGroup(
            pnlValidacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtValEj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValEj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtValEj3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlComprobante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMPROBANTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        lblNroFactura.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        lblNroFactura.setText("NRO. FACTURA DEL PROVEEDOR");

        pnlFormaPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMA DE PAGO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        javax.swing.GroupLayout pnlFormaPagoLayout = new javax.swing.GroupLayout(pnlFormaPago);
        pnlFormaPago.setLayout(pnlFormaPagoLayout);
        pnlFormaPagoLayout.setHorizontalGroup(
            pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFormasPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFormaPagoLayout.setVerticalGroup(
            pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFormasPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDestinoPago.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        grpBtnFormaPago.add(rbtnCaja);
        rbtnCaja.setText("Caja - Caja Principal");

        grpBtnFormaPago.add(rbtnCtaBancaria);
        rbtnCtaBancaria.setText("Cuenta bancaria - BCP Cta. Cte.");

        javax.swing.GroupLayout pnlDestinoPagoLayout = new javax.swing.GroupLayout(pnlDestinoPago);
        pnlDestinoPago.setLayout(pnlDestinoPagoLayout);
        pnlDestinoPagoLayout.setHorizontalGroup(
            pnlDestinoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDestinoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCaja)
                    .addComponent(rbtnCtaBancaria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestinoPagoLayout.setVerticalGroup(
            pnlDestinoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnCtaBancaria)
                .addContainerGap())
        );

        pnlTotales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTALES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        lblSubtotal.setText("Subtotal:");

        lblCantSubTotal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCantSubTotal.setText("S/ 913.98");

        lblIGV.setText("IGV;");

        lblCantIGV.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblCantIGV.setText("S/ 164.52");

        lblTotal.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblTotal.setText("TOTAL");

        lblCantTotal.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblCantTotal.setText("S/ 1,078.50 ");

        javax.swing.GroupLayout pnlTotalesLayout = new javax.swing.GroupLayout(pnlTotales);
        pnlTotales.setLayout(pnlTotalesLayout);
        pnlTotalesLayout.setHorizontalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(lblCantTotal))
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantIGV, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlTotalesLayout.setVerticalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblCantSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIGV)
                    .addComponent(lblCantIGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblCantTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrarVenta.setBackground(new java.awt.Color(153, 51, 0));
        btnRegistrarVenta.setText("REGISTRAR COMPRA");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblFechaCompra.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        lblFechaCompra.setText("FECHA DE LA COMPRA");

        javax.swing.GroupLayout pnlPlazoDiasLayout = new javax.swing.GroupLayout(pnlPlazoDias);
        pnlPlazoDias.setLayout(pnlPlazoDiasLayout);
        pnlPlazoDiasLayout.setHorizontalGroup(
            pnlPlazoDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPlazoDiasLayout.setVerticalGroup(
            pnlPlazoDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlComprobanteLayout = new javax.swing.GroupLayout(pnlComprobante);
        pnlComprobante.setLayout(pnlComprobanteLayout);
        pnlComprobanteLayout.setHorizontalGroup(
            pnlComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprobanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFormaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDestinoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFacturaProveedor)
                    .addComponent(jdcFechaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlComprobanteLayout.createSequentialGroup()
                        .addGroup(pnlComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroFactura)
                            .addComponent(lblFechaCompra))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlPlazoDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlComprobanteLayout.setVerticalGroup(
            pnlComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprobanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNroFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pnlFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDestinoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pnlPlazoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDetalleProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAgregarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlValidaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlValidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        registrarCompra();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        agregarProducto();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    // ============================================================
    // Conexión del formulario con Service/ProcesoCompra.
    // Nada de lo siguiente accede a DAO ni a PostgreSQL directamente.
    // ============================================================
    private void configurarComponentes() {
        lblNombreVend.setText(SesionUsuario.actual().getNombreCompleto());
        lblFechaHora.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yy - hh:mm a")));

        configurarCaja();
        configurarTabla();
        configurarSpinnerCantidad();
        configurarSpinnerPlazoDias();
        configurarFechaCompra();
        configurarComboProveedor();
        configurarComboOrdenCompra();
        configurarComboProductos();
        configurarComboFormasPago();
        limpiarValidaciones();
        recalcularTotales();

        txtValEj1.setEditable(false);
        txtValEj2.setEditable(false);
        txtValEj3.setEditable(false);

        // A diferencia de Ventas, el costo unitario de compra SÍ es editable:
        // no existe un precio de compra en el catálogo (Producto solo tiene
        // precioVenta), así que lo captura el usuario en cada compra.
        txtPrecioUnitario.setEditable(true);

    }

    // Caja abierta y cuenta bancaria activa, igual que en FrmVentas.
    // NOTA: el formulario solo tiene un radio para "Cuenta Bancaria" (no una
    // lista), así que si hay varias cuentas activas se usa la primera —
    // mismo criterio ya adoptado en FrmVentas, no se agrega un selector nuevo.
    private void configurarCaja() {
        Optional<Caja> caja = tesoreriaService.obtenerCajaAbierta();
        if (caja.isPresent()) {
            cajaAbierta = caja.get();
            lblCaja.setText(cajaAbierta.getNombre() + " - Abierta");
            rbtnCaja.setText("Caja - " + cajaAbierta.getNombre());
            rbtnCaja.setEnabled(true);
        } else {
            cajaAbierta = null;
            lblCaja.setText("Sin caja abierta");
            rbtnCaja.setText("Caja (no hay ninguna abierta)");
            rbtnCaja.setEnabled(false);
        }

        List<CuentaBancaria> cuentas = tesoreriaService.listarCuentasBancariasActivas();
        if (!cuentas.isEmpty()) {
            cuentaBancariaActiva = cuentas.get(0);
            rbtnCtaBancaria.setText("Cuenta bancaria - " + cuentaBancariaActiva.getBanco()
                    + " " + cuentaBancariaActiva.getAlias());
            rbtnCtaBancaria.setEnabled(true);
        } else {
            cuentaBancariaActiva = null;
            rbtnCtaBancaria.setText("Cuenta bancaria (no hay ninguna activa)");
            rbtnCtaBancaria.setEnabled(false);
        }

        if (cajaAbierta != null) {
            rbtnCaja.setSelected(true);
        } else if (cuentaBancariaActiva != null) {
            rbtnCtaBancaria.setSelected(true);
        }
    }

    private void configurarTabla() {

        tblDetProducto.setModel(modeloDetalle);

        // ==========================================================
        // RENDERER GENERAL DE LA TABLA
        // ==========================================================
        DefaultTableCellRenderer rendererProducto
                = new DefaultTableCellRenderer() {

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                String texto = "";

                if (value instanceof Producto producto) {
                    texto = producto.getCodigo()
                            + " - "
                            + producto.getNombre();
                } else if (value != null) {
                    texto = value.toString();
                }

                return super.getTableCellRendererComponent(
                        table,
                        texto,
                        isSelected,
                        hasFocus,
                        row,
                        column
                );
            }
        };

        tblDetProducto.getColumnModel()
                .getColumn(0)
                .setCellRenderer(rendererProducto);

        // ==========================================================
        // RENDERER DE CANTIDAD
        // ==========================================================
        DefaultTableCellRenderer rendererCantidad
                = new DefaultTableCellRenderer() {

            {
                setHorizontalAlignment(SwingConstants.RIGHT);
            }

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                String texto = "";

                if (value instanceof BigDecimal cantidad) {
                    texto = cantidad.stripTrailingZeros()
                            .toPlainString();
                } else if (value != null) {
                    texto = value.toString();
                }

                return super.getTableCellRendererComponent(
                        table,
                        texto,
                        isSelected,
                        hasFocus,
                        row,
                        column
                );
            }
        };

        tblDetProducto.getColumnModel()
                .getColumn(1)
                .setCellRenderer(rendererCantidad);

        // ==========================================================
        // RENDERER DE MONEDA
        // ==========================================================
        DefaultTableCellRenderer rendererMoneda
                = new DefaultTableCellRenderer() {

            {
                setHorizontalAlignment(SwingConstants.RIGHT);
            }

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                String texto = "";

                if (value instanceof BigDecimal monto) {

                    texto = "S/ "
                            + FORMATO_MONEDA.format(monto);

                } else if (value != null) {

                    try {

                        BigDecimal monto
                                = new BigDecimal(
                                        value.toString()
                                                .replace("S/", "")
                                                .replace(",", "")
                                                .trim()
                                );

                        texto = "S/ "
                                + FORMATO_MONEDA.format(monto);

                    } catch (NumberFormatException ex) {

                        texto = value.toString();
                    }
                }

                return super.getTableCellRendererComponent(
                        table,
                        texto,
                        isSelected,
                        hasFocus,
                        row,
                        column
                );
            }
        };

        tblDetProducto.getColumnModel()
                .getColumn(2)
                .setCellRenderer(rendererMoneda);

        tblDetProducto.getColumnModel()
                .getColumn(3)
                .setCellRenderer(rendererMoneda);

        // ==========================================================
        // ACTUALIZAR SUBTOTALES AL EDITAR COSTO
        // ==========================================================
        modeloDetalle.addTableModelListener(e -> {

            if (e.getType() == TableModelEvent.UPDATE
                    && (e.getColumn() == 2
                    || e.getColumn() == TableModelEvent.ALL_COLUMNS)) {

                actualizarSubtotalesDesdeTabla();
            }
        });
    }

    private void configurarSpinnerCantidad() {
        spnCantidad.setModel(new SpinnerNumberModel(1, 1, 99999, 1));
    }

    // pnlPlazoDias venía vacío en el diseño (un panel de 0x0, sin ningún
    // control adentro) — sin esto es imposible capturar el plazo que exige
    // CompraServiceImpl para crédito, así que se agrega el único control que
    // faltaba (misma idea que el aviso agregado a pnlAvisoCtaCobrar en
    // FrmVentas: rellenar un placeholder vacío, no rediseñar el formulario).
    private JSpinner spnPlazoDias;

    private void configurarSpinnerPlazoDias() {
        pnlPlazoDias.setLayout(new BorderLayout(6, 0));
        javax.swing.JLabel lblPlazo = new javax.swing.JLabel("Plazo (días):");
        lblPlazo.setFont(lblPlazo.getFont().deriveFont(11f));
        spnPlazoDias = new JSpinner(new SpinnerNumberModel(30, 1, 360, 1));
        pnlPlazoDias.add(lblPlazo, BorderLayout.WEST);
        pnlPlazoDias.add(spnPlazoDias, BorderLayout.CENTER);
    }

    private void configurarFechaCompra() {
        jdcFechaCompra.setDate(new Date());
    }

    // cmbProveedor: editable + ComboAutoFiltro sobre
    // ProveedorService.buscarActivosPorRazonSocialORucParcial(texto).
    private void configurarComboProveedor() {
        cmbProveedor.setModel(new DefaultComboBoxModel<>());
        ComboAutoFiltro.mejorarCombo(cmbProveedor, proveedorService::buscarActivosPorRazonSocialORucParcial);
        cmbProveedor.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED && e.getItem() instanceof Proveedor proveedor) {
                mostrarProveedorSeleccionado(proveedor);
                actualizarOrdenesDelProveedor(proveedor);
            }
        });
        limpiarProveedorMostrado();
    }

    private void mostrarProveedorSeleccionado(Proveedor proveedor) {
        lblDocumento.setText("RUC " + proveedor.getRuc());
        lblNombreCliente.setText(proveedor.getRazonSocial());
        tblTelefono.setText("Tel. " + (proveedor.getTelefono() == null ? "-" : proveedor.getTelefono()));
    }

    private void limpiarProveedorMostrado() {
        lblDocumento.setText("RUC —");
        lblNombreCliente.setText("Selecciona un proveedor");
        tblTelefono.setText("Tel. —");
    }

    // cmbOrdenCompra: SIN ComboAutoFiltro (lista corta) — solo órdenes
    // APROBADA, y además acotada al proveedor seleccionado (una orden le
    // pertenece a un proveedor puntual). Siempre incluye la opción "sin
    // orden" (compra directa), que es el caso más común.
    private void configurarComboOrdenCompra() {

        ordenesAprobadas
                = ordenCompraService.listarPorEstado(
                        EstadoOrdenCompra.APROBADA
                );

        DefaultComboBoxModel<OrdenCompra> modelo
                = new DefaultComboBoxModel<>();

        modelo.addElement(null);

        for (OrdenCompra orden : ordenesAprobadas) {
            modelo.addElement(orden);
        }

        cmbOrdenCompra.setModel(modelo);

        cmbOrdenCompra.setSelectedItem(null);

        cmbOrdenCompra.setRenderer(
                new DefaultListCellRenderer() {

            @Override
            public java.awt.Component getListCellRendererComponent(
                    JList<?> list,
                    Object value,
                    int index,
                    boolean isSelected,
                    boolean cellHasFocus) {

                Object mostrado
                        = value == null
                                ? "— Compra directa, sin orden previa —"
                                : value;

                return super.getListCellRendererComponent(
                        list,
                        mostrado,
                        index,
                        isSelected,
                        cellHasFocus
                );
            }
        }
        );

        cmbOrdenCompra.addItemListener(e -> {

            if (e.getStateChange() != ItemEvent.SELECTED) {
                return;
            }

            Object seleccionado = e.getItem();

            if (seleccionado instanceof OrdenCompra orden) {

                cargarDetallesDeOrdenCompra(orden);

                cmbProductos.setEnabled(false);
                spnCantidad.setEnabled(false);
                txtPrecioUnitario.setEnabled(false);
                btnAgregarProducto.setEnabled(false);

            } else {

                limpiarDetallesCompra();

                cmbProductos.setEnabled(true);
                spnCantidad.setEnabled(true);
                txtPrecioUnitario.setEnabled(true);
                btnAgregarProducto.setEnabled(true);
            }
        });
    }

    private void cargarDetallesDeOrdenCompra(OrdenCompra orden) {

        limpiarValidaciones();
        limpiarDetallesCompra();

        List<DetalleOrdenCompra> detallesOrden
                = orden.getDetalles();

        if (detallesOrden == null
                || detallesOrden.isEmpty()) {

            mostrarValidacion(
                    "La orden de compra seleccionada "
                    + "no contiene productos."
            );

            return;
        }

        for (DetalleOrdenCompra detalleOrden : detallesOrden) {

            Producto producto
                    = productoService.buscarPorId(
                            detalleOrden.getIdProducto()
                    );

            if (producto == null) {

                mostrarValidacion(
                        "No se encontró el producto "
                        + detalleOrden.getIdProducto()
                        + " asociado a la orden de compra."
                );

                limpiarDetallesCompra();

                return;
            }

            modeloDetalle.addRow(
                    new Object[]{
                        producto,
                        detalleOrden.getCantidad(),
                        null,
                        null
                    }
            );
        }

        recalcularTotalesDesdeTabla();
    }

    private void limpiarDetallesCompra() {

        detalles.clear();

        modeloDetalle.setRowCount(0);

        recalcularTotales();
    }

    private void actualizarSubtotalesDesdeTabla() {

        for (int fila = 0;
                fila < modeloDetalle.getRowCount();
                fila++) {

            Object cantidadObj
                    = modeloDetalle.getValueAt(fila, 1);

            Object costoObj
                    = modeloDetalle.getValueAt(fila, 2);

            if (cantidadObj == null
                    || costoObj == null
                    || costoObj.toString().trim().isEmpty()) {

                modeloDetalle.setValueAt(
                        null,
                        fila,
                        3
                );

                continue;
            }

            try {

                BigDecimal cantidad
                        = new BigDecimal(
                                cantidadObj.toString()
                        );

                BigDecimal costo
                        = new BigDecimal(
                                costoObj.toString()
                                        .replace("S/", "")
                                        .replace(",", "")
                                        .trim()
                        );

                if (costo.compareTo(BigDecimal.ZERO) < 0) {

                    modeloDetalle.setValueAt(
                            null,
                            fila,
                            3
                    );

                    continue;
                }

                BigDecimal subtotal
                        = cantidad.multiply(costo)
                                .setScale(
                                        2,
                                        RoundingMode.HALF_UP
                                );

                modeloDetalle.setValueAt(
                        subtotal,
                        fila,
                        3
                );

            } catch (NumberFormatException ex) {

                modeloDetalle.setValueAt(
                        null,
                        fila,
                        3
                );
            }
        }

        recalcularTotalesDesdeTabla();
    }

    private void recalcularTotalesDesdeTabla() {

        BigDecimal subtotal = BigDecimal.ZERO;

        for (int fila = 0;
                fila < modeloDetalle.getRowCount();
                fila++) {

            Object subtotalObj
                    = modeloDetalle.getValueAt(fila, 3);

            if (subtotalObj == null) {
                continue;
            }

            try {

                BigDecimal valor
                        = new BigDecimal(
                                subtotalObj.toString()
                                        .replace("S/", "")
                                        .replace(",", "")
                                        .trim()
                        );

                subtotal = subtotal.add(valor);

            } catch (NumberFormatException ignored) {
            }
        }

        subtotal
                = subtotal.setScale(
                        2,
                        RoundingMode.HALF_UP
                );

        BigDecimal igv
                = subtotal.compareTo(BigDecimal.ZERO) == 0
                ? BigDecimal.ZERO.setScale(
                        2,
                        RoundingMode.HALF_UP
                )
                : CalculadoraImpuestos
                        .calcularIGVDesdeSubtotal(subtotal);

        BigDecimal total
                = subtotal.compareTo(BigDecimal.ZERO) == 0
                ? BigDecimal.ZERO.setScale(
                        2,
                        RoundingMode.HALF_UP
                )
                : CalculadoraImpuestos
                        .calcularTotalConIgv(subtotal);

        lblCantSubTotal.setText(
                "S/ " + FORMATO_MONEDA.format(subtotal)
        );

        lblCantIGV.setText(
                "S/ " + FORMATO_MONEDA.format(igv)
        );

        lblCantTotal.setText(
                "S/ " + FORMATO_MONEDA.format(total)
        );
    }

    private void actualizarOrdenesDelProveedor(Proveedor proveedor) {
        DefaultComboBoxModel<OrdenCompra> modelo = new DefaultComboBoxModel<>();
        modelo.addElement(null); // "— Compra directa, sin orden previa —"
        for (OrdenCompra orden : ordenesAprobadas) {
            if (orden.getIdProveedor() == proveedor.getIdProveedor()) {
                modelo.addElement(orden);
            }
        }
        cmbOrdenCompra.setModel(modelo);
        cmbOrdenCompra.setSelectedItem(null);
    }

    // cmbProductos: editable + ComboAutoFiltro sobre
    // ProductoService.buscarActivosPorNombreOCodigoParcial(texto).
    // A diferencia de Ventas, txtPrecioUnitario NO se autocompleta: es el
    // costo de compra, que el catálogo no guarda (Producto solo tiene
    // precioVenta), así que queda vacío y editable para que el usuario lo
    // ingrese.
    private void configurarComboProductos() {
        cmbProductos.setModel(new DefaultComboBoxModel<>());
        ComboAutoFiltro.mejorarCombo(cmbProductos, productoService::buscarActivosPorNombreOCodigoParcial);
        cmbProductos.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED && e.getItem() instanceof Producto) {
                txtPrecioUnitario.setText("");
            }
        });
    }

    // cmbFormasPago: lista fija, sin ComboAutoFiltro. Crédito/contado se
    // decide siempre con FormaPago.isEsCredito(), nunca por nombre.
    private void configurarComboFormasPago() {
        cmbFormasPago.setModel(new DefaultComboBoxModel<>(formaPagoService.listar().toArray(new FormaPago[0])));
        cmbFormasPago.setSelectedItem(null);
        cmbFormasPago.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                actualizarVisibilidadPago();
            }
        });
        actualizarVisibilidadPago();
    }

    // Contado: se muestra pnlDestinoPago (caja/banco) y se oculta pnlPlazoDias.
    // Crédito: al revés. CompraServiceImpl ya fuerza plazoDias=null si no es
    // crédito, así que aquí no hace falta limpiar el spinner manualmente.
    private void actualizarVisibilidadPago() {
        Object seleccion = cmbFormasPago.getSelectedItem();
        boolean esCredito = seleccion instanceof FormaPago fp && fp.isEsCredito();

        pnlDestinoPago.setVisible(!esCredito);
        pnlPlazoDias.setVisible(esCredito);

        pnlComprobante.revalidate();
        pnlComprobante.repaint();
    }

    // ------------------------------------------------------------------
    // Detalle de productos en memoria
    // ------------------------------------------------------------------
    private void agregarProducto() {

        limpiarValidaciones();

        if (cmbOrdenCompra.getSelectedItem() instanceof OrdenCompra) {

            mostrarValidacion(
                    "La compra está asociada a una orden. "
                    + "Los productos ya fueron cargados desde la orden."
            );

            return;
        }

        Object seleccion
                = cmbProductos.getSelectedItem();

        if (!(seleccion instanceof Producto producto)) {

            mostrarValidacion(
                    "Selecciona un producto del listado."
            );

            return;
        }

        BigDecimal cantidad;

        try {

            cantidad
                    = new BigDecimal(
                            spnCantidad
                                    .getValue()
                                    .toString()
                    );

        } catch (NumberFormatException ex) {

            mostrarValidacion(
                    "La cantidad es inválida."
            );

            return;
        }

        if (cantidad.compareTo(BigDecimal.ZERO) <= 0) {

            mostrarValidacion(
                    "La cantidad debe ser mayor a cero."
            );

            return;
        }

        BigDecimal costoUnitario;

        try {

            costoUnitario
                    = new BigDecimal(
                            txtPrecioUnitario
                                    .getText()
                                    .trim()
                                    .replace(",", "")
                    );

        } catch (NumberFormatException
                | NullPointerException ex) {

            mostrarValidacion(
                    "El costo unitario es inválido."
            );

            return;
        }

        if (costoUnitario.compareTo(BigDecimal.ZERO) < 0) {

            mostrarValidacion(
                    "El costo unitario es inválido."
            );

            return;
        }

        BigDecimal subtotal
                = cantidad.multiply(costoUnitario)
                        .setScale(
                                2,
                                RoundingMode.HALF_UP
                        );

        modeloDetalle.addRow(
                new Object[]{
                    producto,
                    cantidad,
                    costoUnitario,
                    subtotal
                }
        );

        recalcularDetallesDesdeTabla();
        recalcularTotalesDesdeTabla();

        cmbProductos.setSelectedItem(null);
        txtPrecioUnitario.setText("");
        spnCantidad.setValue(1);
    }

    private boolean recalcularDetallesDesdeTabla() {

        detalles.clear();

        boolean valido = true;

        for (int fila = 0;
                fila < modeloDetalle.getRowCount();
                fila++) {

            Object productoObj
                    = modeloDetalle.getValueAt(fila, 0);

            Object cantidadObj
                    = modeloDetalle.getValueAt(fila, 1);

            Object costoObj
                    = modeloDetalle.getValueAt(fila, 2);

            if (!(productoObj instanceof Producto producto)) {

                valido = false;
                continue;
            }

            if (cantidadObj == null
                    || costoObj == null
                    || costoObj.toString().trim().isEmpty()) {

                valido = false;
                continue;
            }

            try {

                BigDecimal cantidad
                        = new BigDecimal(
                                cantidadObj.toString()
                        );

                BigDecimal costo
                        = new BigDecimal(
                                costoObj.toString()
                                        .replace("S/", "")
                                        .replace(",", "")
                                        .trim()
                        );

                if (cantidad.compareTo(BigDecimal.ZERO) <= 0
                        || costo.compareTo(BigDecimal.ZERO) < 0) {

                    valido = false;
                    continue;
                }

                detalles.add(
                        new DetalleCompra(
                                producto.getIdProducto(),
                                cantidad,
                                costo
                        )
                );

            } catch (NumberFormatException ex) {

                valido = false;
            }
        }

        return valido;
    }

    // El costo unitario NO incluye IGV (al revés que Ventas): se usa
    // CalculadoraImpuestos.calcularIGVDesdeSubtotal/calcularTotalConIgv, la
    // misma fórmula centralizada que usa CompraServiceImpl — no se repite acá.
    private void recalcularTotales() {
        BigDecimal subtotal = BigDecimal.ZERO;
        for (DetalleCompra d : detalles) {
            subtotal = subtotal.add(d.getSubtotal());
        }
        subtotal = subtotal.setScale(2, RoundingMode.HALF_UP);

        BigDecimal igv = subtotal.compareTo(BigDecimal.ZERO) == 0
                ? BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP)
                : CalculadoraImpuestos.calcularIGVDesdeSubtotal(subtotal);
        BigDecimal total = subtotal.compareTo(BigDecimal.ZERO) == 0
                ? BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP)
                : CalculadoraImpuestos.calcularTotalConIgv(subtotal);

        lblCantSubTotal.setText("S/ " + FORMATO_MONEDA.format(subtotal));
        lblCantIGV.setText("S/ " + FORMATO_MONEDA.format(igv));
        lblCantTotal.setText("S/ " + FORMATO_MONEDA.format(total));
    }

    // ------------------------------------------------------------------
    // Registrar compra — decide la variante de ProcesoCompra según forma de pago
    // ------------------------------------------------------------------
    private void registrarCompra() {
        limpiarValidaciones();

        Object proveedorSel = cmbProveedor.getSelectedItem();
        if (!(proveedorSel instanceof Proveedor proveedor)) {
            mostrarValidacion("Selecciona un proveedor.");
            return;
        }

        if (txtFacturaProveedor.getText() == null || txtFacturaProveedor.getText().isBlank()) {
            mostrarValidacion("El número de factura del proveedor es obligatorio.");
            return;
        }

        if (modeloDetalle.getRowCount() == 0) {

            mostrarValidacion(
                    "La compra debe tener al menos un producto."
            );

            return;
        }

        if (!recalcularDetallesDesdeTabla()
                || detalles.size() != modeloDetalle.getRowCount()) {

            mostrarValidacion(
                    "Completa correctamente el costo unitario "
                    + "de todos los productos."
            );

            return;
        }

        Object formaPagoSel = cmbFormasPago.getSelectedItem();
        if (!(formaPagoSel instanceof FormaPago formaPago)) {
            mostrarValidacion("Selecciona una forma de pago.");
            return;
        }

        if (jdcFechaCompra.getDate() == null) {
            mostrarValidacion("Selecciona la fecha de la compra.");
            return;
        }

        Compra compra = new Compra(proveedor.getIdProveedor(), formaPago.getIdFormaPago(),
                txtFacturaProveedor.getText().trim(), SesionUsuario.actual().getIdUsuario());
        compra.setFecha(jdcFechaCompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());

        Object ordenSel = cmbOrdenCompra.getSelectedItem();
        if (ordenSel instanceof OrdenCompra orden) {
            compra.setIdOrdenCompra(orden.getIdOrdenCompra());
        }

        if (formaPago.isEsCredito()) {
            compra.setPlazoDias((Integer) spnPlazoDias.getValue());
        }

        for (DetalleCompra d : detalles) {
            compra.agregarDetalle(d);
        }

        RespuestaOperacion<Integer> resultado;
        if (formaPago.isEsCredito()) {
            resultado = procesoCompra.registrarCompraCredito(compra);
        } else if (rbtnCaja.isSelected()) {
            if (cajaAbierta == null) {
                mostrarValidacion("No hay una caja abierta para pagar al contado.");
                return;
            }
            resultado = procesoCompra.registrarCompraContadoCaja(compra, cajaAbierta.getIdCaja());
        } else if (rbtnCtaBancaria.isSelected()) {
            if (cuentaBancariaActiva == null) {
                mostrarValidacion("No hay una cuenta bancaria activa para pagar.");
                return;
            }
            resultado = procesoCompra.registrarCompraContadoBanco(compra, cuentaBancariaActiva.getIdCuentaBancaria());
        } else {
            mostrarValidacion("Selecciona caja o cuenta bancaria para el pago al contado.");
            return;
        }

        if (!resultado.isExito()) {
            mostrarValidacion(resultado.getMensaje());
            return;
        }

        JOptionPane.showMessageDialog(this, "Compra N° " + resultado.getResultado() + " registrada correctamente.");
        limpiarFormularioTrasRegistro();
    }

    private void limpiarFormularioTrasRegistro() {
        detalles.clear();
        modeloDetalle.setRowCount(0);
        recalcularTotales();

        cmbProveedor.setSelectedItem(null);
        limpiarProveedorMostrado();
        cmbOrdenCompra.setModel(new DefaultComboBoxModel<>());
        cmbOrdenCompra.addItem(null);
        cmbOrdenCompra.setSelectedItem(null);
        cmbProductos.setSelectedItem(null);
        txtPrecioUnitario.setText("");
        spnCantidad.setValue(1);
        txtFacturaProveedor.setText("");
        jdcFechaCompra.setDate(new Date());
        cmbFormasPago.setSelectedItem(null);
        spnPlazoDias.setValue(30);
        actualizarVisibilidadPago();
    }

    // ------------------------------------------------------------------
    // pnlValidaciones: los errores de RespuestaOperacion (y las validaciones
    // propias del formulario) se muestran acá, nunca con JOptionPane.
    // ------------------------------------------------------------------
    private void mostrarValidacion(String mensaje) {
        txtValEj1.setText(mensaje);
        txtValEj2.setText("");
        txtValEj3.setText("");
    }

    private void limpiarValidaciones() {
        txtValEj1.setText("");
        txtValEj2.setText("");
        txtValEj3.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<FormaPago> cmbFormasPago;
    private javax.swing.JComboBox<OrdenCompra> cmbOrdenCompra;
    private javax.swing.JComboBox<Producto> cmbProductos;
    private javax.swing.JComboBox<Proveedor> cmbProveedor;
    private javax.swing.ButtonGroup grpBtnFormaPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcFechaCompra;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblCantIGV;
    private javax.swing.JLabel lblCantSubTotal;
    private javax.swing.JLabel lblCantTotal;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaCompra;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreVend;
    private javax.swing.JLabel lblNroFactura;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlAgregarProd;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlClienteBuscado;
    private javax.swing.JPanel pnlComprobante;
    private javax.swing.JPanel pnlDestinoPago;
    private javax.swing.JPanel pnlDetalleProducto;
    private javax.swing.JPanel pnlFormaPago;
    private javax.swing.JPanel pnlOrdenCompra;
    private javax.swing.JPanel pnlPlazoDias;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JPanel pnlTotales;
    private javax.swing.JPanel pnlValidaciones;
    private javax.swing.JRadioButton rbtnCaja;
    private javax.swing.JRadioButton rbtnCtaBancaria;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblDetProducto;
    private javax.swing.JLabel tblTelefono;
    private javax.swing.JTextField txtFacturaProveedor;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtValEj1;
    private javax.swing.JTextField txtValEj2;
    private javax.swing.JTextField txtValEj3;
    // End of variables declaration//GEN-END:variables
}
